Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -27,6 +27,13 @@ jobs:
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
         terraform_wrapper: false
 
+    # Run a terraform validate for push and PR on non-main branch
+    # Run even if formatting fails
+    - name: Terraform Validate
+      id: validate
+      if: github.ref != 'refs/heads/main' && (success() || failure())
+      run: terraform validate -no-color
+
     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
     - name: Terraform Init
       run: terraform init
